# Generated by Django 2.0 on 2019-06-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(2, '支付宝'), (1, '货到付款')], default=1, verbose_name='支付方式'),
        ),
    ]
