# Generated by Django 2.0 on 2019-07-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20190701_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='share_code',
        ),
    ]
